apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: somapp
  name: somapp
  namespace: som-context
spec:
  replicas: 1
  selector:
    matchLabels:
      app: somapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: somapp
    spec:
      containers:
      - image: somanath89/somshimage:latest
        name: somshimage
        ports:
        - containerPort: 80
        resources: {}
status: {}
